version: '3'

services:
  enghouse-svc:
    image: enghouse-oke-app
    environment:
      - DB_USERNAME
      - DB_PASSWORD
      - DB_TNS_SERVICE_NAME
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./${TNS_ADMIN}
        target: /wallet

